services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - API_KEY=${API_KEY}
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/sapon/Desktop/docker-compose2/volumes:/data
  www:
    container_name: apache2
    image: ubuntu/apache2
    restart: always
    ports:
      - "80:80"
      