services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - "5432:5432"
    volumes:
      - ./volumen_db:/var/lib/postgresql/data
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
  www:
    container_name: apache2
    image: ubuntu/apache2
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./volumen_apache2:/var/www/html
    command: >
      bash -c "apt-get update && 
               apt-get install -y php8.3 php8.3-pgsql libapache2-mod-php &&
               service apache2 restart && 
               tail -f /dev/null"
  grafana_container:
    image: grafana/grafana:11.0.0
    container_name: grafana_container
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_config:/etc/grafana
    depends_on:
      - db

      
